version: "3.9"
services:
  app:
    build: .
    command: "go run main.go"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
